# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_auto_20180305_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='bio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
