# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20180304_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=100),
        ),
    ]
